namespace: do

resources:
  - deployment.yaml
  - service.yaml

replacements:
  - source:
      kind: Deployment
      name: nginx-deployment
      fieldPath: spec.template.spec.containers.[name=nginx].image
    targets:
      - select:
          kind: Deployment
          name: nginx-deployment
        fieldPaths:
          - spec.template.metadata.annotations.diun\.metadata\.image_name